name: Setup Node.js with .nvmrc
description: Reads the .nvmrc file and sets up the corresponding Node.js version
runs:
  using: composite
  steps:
    - name: Read .nvmrc
      run: echo "node-version=$(cat .nvmrc)" >> $GITHUB_ENV
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node-version }}
        cache: 'npm'
