[package]
name = "liquidation-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.6", features = ["postgres"] }
dotenvy = "0.15"
log = "0.4.25"
env_logger = "0.11.6"
stellar-rpc-client = "22.0.0"
tokio = { version = "1.45.0", features = ["full"] }
