name: Setup Rust and Stellar
description: Installs Rust toolchain and Stellar CLI
inputs:
  stellar_version:
    description: The version of Stellar CLI to install
    required: false
    default: "22.0.0"
runs:
  using: composite
  steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        targets: wasm32-unknown-unknown

    - name: Rust cache
      uses: stellar/actions/rust-cache@main

    - name: Install Stellar CLI
      run: |
        cargo install --locked stellar-cli --version ${{ inputs.stellar_version }} --features opt
      shell: bash
