name: Build and Deploy
on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Setup Rust and Stellar
        uses: ./.github/actions/setup-rust-stellar

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Build contracts
        run: make build

      - name: Install and build
        env:
          SOROBAN_NETWORK: testnet
          SOROBAN_ACCOUNT: ${{ secrets.SOROBAN_ACCOUNT }}
          SOROBAN_SECRET_KEY: ${{ secrets.SOROBAN_SECRET_KEY }}
          CONTRACT_ID_LOAN_MANAGER: ${{ secrets.CONTRACT_ID_LOAN_MANAGER }}
          CONTRACT_ID_POOL_XLM: ${{ secrets.CONTRACT_ID_POOL_XLM }}
          CONTRACT_ID_POOL_WBTC: ${{ secrets.CONTRACT_ID_POOL_WBTC }}
          CONTRACT_ID_POOL_WETH: ${{ secrets.CONTRACT_ID_POOL_WETH }}
          CONTRACT_ID_POOL_USDC: ${{ secrets.CONTRACT_ID_POOL_USDC }}
          CONTRACT_ID_POOL_EURC: ${{ secrets.CONTRACT_ID_POOL_EURC }}
        run: |
          npm ci
          npm run upgrade

      - name: Build Astro app
        env:
          PUBLIC_SOROBAN_NETWORK_PASSPHRASE: Test SDF Network ; September 2015
          PUBLIC_SOROBAN_RPC_URL: https://soroban-testnet.stellar.org/
        uses: withastro/action@v2

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
