name: Node.js

on:
  push:
    branches-ignore:
      - main

jobs:

  complete:
    if: always()
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
    - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
      run: exit 1

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: ./.github/actions/setup-node

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test

    - name: Biome lint check
      run: npm run lint:check

    - name: Prettier format check
      run: npm run format:check
