name: "Rust: Format Check"

on:
  push:
    branches-ignore:
      - main

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: ./.github/actions/setup-rust-stellar

      - name: Run rustfmt
        run: cargo fmt -- --check
