name: Verify Build
on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: Setup Rust and Stellar
        uses: ./.github/actions/setup-rust-stellar

      - name: Build contracts
        run: make build

      - name: Run tests
        run: cargo test --release

      - name: Run clippy
        run: cargo clippy -- -D warnings

      - name: Setup env
        run: cp .env.example .env

      - name: Install and build
        env:
          SOROBAN_NETWORK: testnet
          SOROBAN_ACCOUNT: ${{ secrets.SOROBAN_ACCOUNT }}
          SOROBAN_SECRET_KEY: ${{ secrets.SOROBAN_SECRET_KEY }}
        run: |
          npm install
          npm run init

      - name: Build Astro app
        env:
          PUBLIC_SOROBAN_NETWORK_PASSPHRASE: Test SDF Network ; September 2015
          PUBLIC_SOROBAN_RPC_URL: https://soroban-testnet.stellar.org/
        uses: withastro/action@v2
